# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGeLTptypIvb8grdxr_t8mHaEmOEVeze
"""

# ========================
# 1. DRIVE MOUNT
# ========================
from google.colab import drive
drive.mount('/content/drive')

from unsloth import FastLanguageModel
import torch
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
import os
import evaluate
from tqdm import tqdm
from sentence_transformers import SentenceTransformer, util

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    confusion_matrix
)
os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

import json

config_path = "/content/drive/MyDrive/config.json" if os.path.exists("/content/drive/MyDrive") else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "config.json")
try:
    with open(config_path, "r", encoding="utf-8") as f:
        config_data = json.load(f)
        bigvul_config = config_data.get("Training", {}).get("BigVul", {})
except Exception:
    bigvul_config = {}

# ÖNCEKİ MODELİNİN KAYITLI OLDUĞU YOL
PREVIOUS_MODEL_PATH = bigvul_config.get("PREVIOUS_MODEL_PATH")

# YENİ MODELİN KAYDEDİLECEĞİ YOL (Üzerine yazmamak için "part2" ekledik)
OUTPUT_DIR = bigvul_config.get("OUTPUT_DIR")
FINAL_SAVE_PATH = os.path.join(OUTPUT_DIR, "qwen-code-final")

# Veriseti Ayarları
DATASET_NAME = "bigvul"
DATASET_LANG = "python"
MAX_SEQ_LENGTH = 1024

# Eğitim Hiperparametreleri
BATCH_SIZE = 64
GRAD_ACCUMULATION = 1
EPOCHS = 1
LEARNING_RATE = 1e-5
LOGGING_STEPS = 50
SAVE_STEPS = 200

EVAL_BATCH_SIZE = 64

use_bf16 = torch.cuda.is_bf16_supported()
use_fp16 = not use_bf16

START_POINT = 0
FINISH_POINT = -1

# ========================
# 1. MODELİ KALDIĞI YERDEN YÜKLEME
# ========================
# Base model olan "Qwen/Qwen2.5..." yerine doğrudan kendi eğittiğin LoRA modelinin yolunu veriyoruz.
# Unsloth, bunun bir LoRA adaptörü olduğunu anlayıp base model + senin ağırlıklarını otomatik birleştirecek.
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=PREVIOUS_MODEL_PATH,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)

raw_dataset = load_dataset(
    "json",
    data_files=bigvul_config.get("TRAIN_DATA_FILE"),
    split="train"
)
if FINISH_POINT == -1:
    FINISH_POINT = len(raw_dataset)
dataset = raw_dataset.select(range(START_POINT, FINISH_POINT))

raw_test_dataset = load_dataset(
    "json",
    data_files=bigvul_config.get("TEST_DATA_FILE"),
    split="train" # Jsonl yüklerken default split genelde train olur, verinizin yapısına göre değiştirebilirsiniz
)

test_dataset = raw_test_dataset

# ========================
# 3. CHAT TEMPLATE APPLY
# ========================
def apply_chat_template(example):
    text = tokenizer.apply_chat_template(
        example["messages"],
        tokenize=False,
        add_generation_prompt=False
    )

    tokens = tokenizer(
        text,
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
    )

    return tokens

dataset = dataset.map(apply_chat_template)
test_dataset = test_dataset.map(apply_chat_template)

# ========================
# 4. EĞİTİM ARGÜMANLARI
# ========================
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUMULATION,
    num_train_epochs=EPOCHS,
    learning_rate=LEARNING_RATE,
    fp16=use_fp16,
    bf16=use_bf16,
    logging_steps=LOGGING_STEPS,
    save_steps=SAVE_STEPS,
    save_total_limit=2,
    optim="adamw_torch_4bit",
    weight_decay=0.01,
    lr_scheduler_type="linear",
    gradient_checkpointing=True,
    dataloader_num_workers=0,
    report_to="none",
    eval_strategy="epoch", # Sadece Validation Loss hesaplayacak
)

# ========================
# 5. TRAINER
# ========================
trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset,
    eval_dataset=test_dataset,
    dataset_text_field=None,
    max_seq_length=MAX_SEQ_LENGTH,
    dataset_num_proc=2,
    packing=True,
    args=training_args,
    # HATA VEREN compute_metrics KISMI BURADAN KALDIRILDI
)

# Bellek temizliği
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

# Eğitimi Başlat
print(f"{START_POINT}'inci veriden itibaren eğitime devam ediliyor...")
trainer.train()

# ========================
# 6. YENİ MODELİ KAYDETME
# ========================
model.save_pretrained(FINAL_SAVE_PATH)
tokenizer.save_pretrained(FINAL_SAVE_PATH)

print(f"Eğitim tamamlandı! Modelin Part-2 hali başarıyla {FINAL_SAVE_PATH} dizinine kaydedildi.")

print("\nEğitim tamamlandı! Şimdi test veri seti üzerinde metrikler hesaplanıyor...")

semantic_model = SentenceTransformer("all-MiniLM-L6-v2")

model.eval()
rouge = evaluate.load("rouge")

target_keyword = "zafiyetli"

# LİSTELER DÖNGÜNÜN DIŞINDA TANIMLANIYOR
pred_classes = []
label_classes = []
decoded_preds = []
decoded_labels = []
semantic_scores = []

tokenizer.padding_side = "left"
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Toplam test edilecek veri sayısını ayarlayabilirsiniz (Örn: Tamamını test etmek için min(...) kısmını kaldırabilirsiniz)
TEST_SIZE = len(raw_test_dataset)
test_subset = raw_test_dataset.select(range(TEST_SIZE))

print(f"\n{len(test_subset)} veri üzerinde toplu (batch) test başlıyor... (Ekran çıktıları gizlendi)")

for i in tqdm(range(0, len(test_subset), EVAL_BATCH_SIZE), desc="Değerlendiriliyor"):
    batch_dict = test_subset[i: i + EVAL_BATCH_SIZE]

    prompts = []
    expected_answers = []

    for msgs in batch_dict["messages"]:
        messages = msgs[:-1]
        expected_answers.append(msgs[-1]["content"])

        prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        prompts.append(prompt)

    inputs = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=MAX_SEQ_LENGTH
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=50,
            max_length=None,  # O uzun kırmızı uyarıları susturur
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id
        )

    input_length = inputs.input_ids.shape[1]
    generated_tokens = outputs[:, input_length:]
    generated_texts = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)

    # Çıktıları listelere ekleme işlemi (Print satırları buradan kaldırıldı)
    for gen_text, exp_ans in zip(generated_texts, expected_answers):
        decoded_preds.append(gen_text)
        decoded_labels.append(exp_ans)

        pred_classes.append(1 if target_keyword in gen_text.lower() else 0)
        label_classes.append(1 if target_keyword in exp_ans.lower() else 0)
        # --- 🔥 SEMANTIC SCORE EKLE ---
        emb1 = semantic_model.encode(gen_text, convert_to_tensor=True)
        emb2 = semantic_model.encode(exp_ans, convert_to_tensor=True)

        score = util.cos_sim(emb1, emb2).item()
        semantic_scores.append(score)

# --------------------------
# SONUÇLARI HESAPLA VE YAZDIR
# --------------------------
acc = accuracy_score(label_classes, pred_classes)
f1 = f1_score(label_classes, pred_classes, zero_division=0)
precision = precision_score(label_classes, pred_classes, zero_division=0)
recall = recall_score(label_classes, pred_classes, zero_division=0)
rouge_results = rouge.compute(predictions=decoded_preds, references=decoded_labels)
avg_semantic = sum(semantic_scores) / len(semantic_scores)


print("\n" + "=" * 40)
print(f" 📊 MODEL TEST SONUÇLARI ({len(test_subset)} ÖRNEK)")
print("=" * 40)
print(f"Accuracy (Doğruluk) : {acc:.4f}")
print(f"F1 Score            : {f1:.4f}")
print(f"Precision (Kesinlik): {precision:.4f}")
print(f"Recall (Duyarlılık) : {recall:.4f}")
print("-" * 40)
print(f"ROUGE-1 (Kelime)    : {rouge_results['rouge1']:.4f}")
print(f"ROUGE-L (Cümle)     : {rouge_results['rougeL']:.4f}")
print("-" * 40)
print(f"Semantic Similarity (Mean): {avg_semantic:.4f}")
print("=" * 40 + "\n")

from google.colab import runtime
runtime.unassign()