# -*- coding: utf-8 -*-
"""UnslothPreTraining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUSIQoaCTz2pkqNU_Qwwq-yiXCJft5P-
"""

# ========================
# 1. DRIVE MOUNT
# ========================
from google.colab import drive
drive.mount('/content/drive')

from unsloth import FastLanguageModel
import torch
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
import os
os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

import json

config_path = "./config.json"
try:
    with open(config_path, "r", encoding="utf-8") as f:
        config_data = json.load(f)
        csn_config = config_data.get("Training", {}).get("CodeSearchNet", {})
except Exception:
    csn_config = {}

MODEL_NAME = csn_config.get("MODEL_NAME")
OUTPUT_DIR = csn_config.get("OUTPUT_DIR")

FINAL_SAVE_PATH = os.path.join(OUTPUT_DIR, "qwen-code-final")  # Final LoRA modelinin kaydedileceği yer

# Veriseti Ayarları
DATASET_NAME = "code_search_net"
DATASET_LANG = "python"
MAX_SEQ_LENGTH = 1024  # Token uzunluğu

# Eğitim Hiperparametreleri (Hız ve VRAM Optimizasyonu)
BATCH_SIZE = 32  # 95GB VRAM için yüksek tutularak eğitim hızlandırıldı.
GRAD_ACCUMULATION = 1  # Efektif Batch Size = 64
EPOCHS = 1
LEARNING_RATE = 2e-5
LOGGING_STEPS = 20
SAVE_STEPS = 200

# LoRA Ayarları
LORA_R = 16
LORA_ALPHA = 32

# Sistem bf16 destekliyorsa otomatik açar (Hızlandırır)
use_bf16 = torch.cuda.is_bf16_supported()
use_fp16 = not use_bf16

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_NAME,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)

# ========================
# 3. LORA ADAPTASYONU
# ========================
model = FastLanguageModel.get_peft_model(
    model,
    r=LORA_R,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    lora_alpha=LORA_ALPHA,
    lora_dropout=0,  # Unsloth optimizasyonu için 0 kalmalı
    bias="none",
    use_gradient_checkpointing="unsloth",  # Maksimum VRAM tasarrufu
    random_state=3407,
)

dataset = load_dataset(
    "json",
    data_files=csn_config.get("DATA_FILE"),
    split="train"
)


# ========================
# CHAT TEMPLATE APPLY
# ========================
def apply_chat_template(example):
    text = tokenizer.apply_chat_template(
        example["messages"],
        tokenize=False
    )

    return tokenizer(
        text,
        truncation=True,
        max_length=MAX_SEQ_LENGTH  # 👈 BUNU KULLAN
    )
dataset = dataset.map(apply_chat_template)

BATCH_SIZE=128
GRAD_ACCUMULATION = 1  # Efektif Batch Size = 64

# ========================
# 5. EĞİTİM ARGÜMANLARI
# ========================
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUMULATION,
    num_train_epochs=EPOCHS,
    learning_rate=LEARNING_RATE,
    fp16=use_fp16,
    bf16=use_bf16,
    logging_steps=LOGGING_STEPS,
    save_steps=SAVE_STEPS,
    save_total_limit=2,
    optim="adamw_torch_4bit",  # VRAM dostu optimizer
    weight_decay=0.01,
    lr_scheduler_type="linear",
    gradient_checkpointing=True,  # VRAM optimizasyonu için eklendi
    dataloader_num_workers=4,     # CPU'dan GPU'ya veri aktarımını hızlandırır
    report_to="none"
)

# ========================
# 6. TRAINER
# ========================
trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    dataset_num_proc=2,
    packing=True,  # Eğitim hızını büyük oranda artırır (Kısa metinleri birleştirir)
    args=training_args,
)

# ========================
# 8. PYTORCH_ALLOC_CONF (Memory Fragmentation Fix)
# ========================
import os
os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"
print("PYTORCH_ALLOC_CONF set to expandable_segments:True")

import torch
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

# Eğitimi Başlat
trainer.train()

# ========================
# 7. MODELİ KAYDETME
# ========================
model.save_pretrained(FINAL_SAVE_PATH)
tokenizer.save_pretrained(FINAL_SAVE_PATH)

print(f"Eğitim tamamlandı! Model başarıyla {FINAL_SAVE_PATH} dizinine kaydedildi.")