# -*- coding: utf-8 -*-
"""UnslothSecureCodeWeb.ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJvUp2rPQt_3qtaBCbIuKYtVledKfzv-
"""

# ========================
# 1. DRIVE MOUNT
# ========================
from google.colab import drive
drive.mount('/content/drive')


from unsloth import FastLanguageModel
from unsloth.chat_templates import train_on_responses_only
import os
import torch
import evaluate
import warnings
from tqdm import tqdm
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
from sentence_transformers import SentenceTransformer, util
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
)

os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

warnings.filterwarnings("ignore", category=FutureWarning)

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.get_device_name(0))

import json

config_path = "./config.json"
try:
    with open(config_path, "r", encoding="utf-8") as f:
        config_data = json.load(f)
        fenrir_config = config_data.get("Training", {}).get("Fenrir", {})
except Exception:
    fenrir_config = {}

PREVIOUS_MODEL_PATH = fenrir_config.get("PREVIOUS_MODEL_PATH")
OUTPUT_DIR = fenrir_config.get("OUTPUT_DIR")
FINAL_SAVE_PATH = os.path.join(OUTPUT_DIR, "fenrir-qwen-final")

DATASET_NAME = "AlicanKiraz0/Cybersecurity-Dataset-Fenrir-v2.1"
MAX_SEQ_LENGTH = 2048

BATCH_SIZE = 64
GRAD_ACCUMULATION = 1
EPOCHS = 1  # Overfit'i önlemek için 10'dan 3'e düşürüldü
LEARNING_RATE = 1e-5
LOGGING_STEPS = 20
SAVE_STEPS = 100

MAX_EVAL_TOKENS = 650
EVAL_BATCH_SIZE = 128

use_bf16 = torch.cuda.is_bf16_supported()
use_fp16 = not use_bf16

# ========================
# 1. MODELİ KALDIĞI YERDEN YÜKLEME
# ========================
# Base model olan "Qwen/Qwen2.5..." yerine doğrudan kendi eğittiğin LoRA modelinin yolunu veriyoruz.
# Unsloth, bunun bir LoRA adaptörü olduğunu anlayıp base model + senin ağırlıklarını otomatik birleştirecek.
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=PREVIOUS_MODEL_PATH,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)

# Yeni veri setinin "System", "User", "Asistant" sütunlarına göre template ayarlaması
def apply_chat_template(example):
    messages = []

    # Sütun isimlerindeki olası büyük/küçük harf farklılıklarını (fallback) tolere ediyoruz
    sys_text = example.get("System", example.get("system", ""))
    user_text = example.get("User", example.get("user", ""))
    ast_text = example.get("Asistant", example.get("assistant", ""))  # Asistant/assistant kontrolü

    if sys_text and str(sys_text).strip():
        messages.append({"role": "system", "content": str(sys_text).strip()})

    if user_text and str(user_text).strip():
        messages.append({"role": "user", "content": str(user_text).strip()})

    if ast_text and str(ast_text).strip():
        messages.append({"role": "assistant", "content": str(ast_text).strip()})

    # KRİTİK ÇÖZÜM: Eğer mesaj listesi boşsa tokenizer'ın çökmesini engelle
    if len(messages) == 0:
        return {"text": ""}

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": text}

# ========================
# 3. VERİ SETİNİ YÜKLEME VE BÖLME
# ========================
print(f"{DATASET_NAME} veri seti yükleniyor...")
# Veri setini indiriyoruz. Genelde custom veri setlerinde sadece "train" split'i bulunur.
full_dataset = load_dataset(DATASET_NAME, split="train")

# Güvenilir bir test süreci için datayı manuel olarak bölelim: %80 Train, %10 Val, %10 Test
train_test_split = full_dataset.train_test_split(test_size=0.2, seed=42)
val_test_split = train_test_split['test'].train_test_split(test_size=0.5, seed=42)

dataset = train_test_split['train']
val_dataset = val_test_split['train']
test_dataset = val_test_split['test']

print("Veri seti ChatML formatına çevriliyor...")
dataset = dataset.map(apply_chat_template)
val_dataset = val_dataset.map(apply_chat_template)
test_dataset = test_dataset.map(apply_chat_template)

# ========================
# 4. EĞİTİM ARGÜMANLARI VE TRAINER
# ========================
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUMULATION,
    num_train_epochs=EPOCHS,
    learning_rate=LEARNING_RATE,
    fp16=use_fp16,
    bf16=use_bf16,
    logging_steps=LOGGING_STEPS,
    save_strategy="epoch", # Her epoch sonu kaydet
    save_total_limit=3, # En son 3 modeli tut                      BURAYI UNUTMAAA
    optim="adamw_8bit",
    weight_decay=0.05, # Overfit'i önlemek için 0.01'den 0.05'e artırıldı
    lr_scheduler_type="cosine",
    gradient_checkpointing=True,
    report_to="none",
    eval_strategy="epoch", # Her epoch sonu eval yap
    dataloader_num_workers=8,  # Windows'ta multiprocessing hatalarını sıfıra indirir
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    eval_dataset=val_dataset, # validation setini verdik
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    dataset_num_proc=4,  # RAM tasarrufu için 2'ye düşürüldü
    packing=False,
    args=training_args,
)

# === KAYIP MASKELEME ===
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
)

# ========================
# 5. EĞİTİMİ BAŞLAT
# ========================
torch.cuda.empty_cache()
print("\n🚀 Eğitime başlanıyor...")
trainer.train()

model.save_pretrained(FINAL_SAVE_PATH)
tokenizer.save_pretrained(FINAL_SAVE_PATH)
print(f"✅ Eğitim tamamlandı! Model {FINAL_SAVE_PATH} dizinine kaydedildi.")

from google.colab import runtime
runtime.unassign()