# -*- coding: utf-8 -*-
"""UnslothSecureCodeWeb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCTi6CP2hcrlXA856ldyR3WZE5_MHrKf
"""

# ========================
# 1. DRIVE MOUNT
# ========================
from google.colab import drive
drive.mount('/content/drive')

from unsloth import FastLanguageModel
from unsloth.chat_templates import train_on_responses_only
import os
import torch
import evaluate
from tqdm import tqdm
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
from sentence_transformers import SentenceTransformer, util
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
)

os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

import json

config_path = "./config.json"
try:
    with open(config_path, "r", encoding="utf-8") as f:
        config_data = json.load(f)
        scw_config = config_data.get("Training", {}).get("SecureCodeWeb", {})
except Exception:
    scw_config = {}

PREVIOUS_MODEL_PATH = scw_config.get("PREVIOUS_MODEL_PATH")
OUTPUT_DIR = scw_config.get("OUTPUT_DIR")
FINAL_SAVE_PATH = os.path.join(OUTPUT_DIR, "securecode-qwen-final")

DATASET_NAME = "scthornton/securecode-web"
MAX_SEQ_LENGTH = 8192

BATCH_SIZE = 8
GRAD_ACCUMULATION = 1
EPOCHS = 10  # Overfit'i önlemek için 10'dan 3'e düşürüldü
LEARNING_RATE = 1e-5
LOGGING_STEPS = 20
SAVE_STEPS = 100

MAX_EVAL_TOKENS = 1024
EVAL_BATCH_SIZE = 16

use_bf16 = torch.cuda.is_bf16_supported()
use_fp16 = not use_bf16

# System Prompt'u dışarıda tanımlıyoruz ki fonksiyon görebilsin
system_message = {
    "role": "system",
    "content": (
        "Sen kıdemli bir uygulama güvenliği mühendisisin. Görevin, sağlanan koddaki potansiyel zafiyetleri OWASP Top 10 standartlarına göre analiz etmek, saldırı vektörlerini (exploit) açıklamak ve ardından güvenli uygulamayı derinlemesine savunma (defense-in-depth) stratejileriyle birlikte sunmaktır."
        "Her zaman:"
        "1) problemi analiz et"
        "2) kök sebebi açıkla"
        "3) çözüm öner"
        "4) kısa ve net yaz"
                )
}

# ========================
# 1. MODELİ KALDIĞI YERDEN YÜKLEME
# ========================
# Base model olan "Qwen/Qwen2.5..." yerine doğrudan kendi eğittiğin LoRA modelinin yolunu veriyoruz.
# Unsloth, bunun bir LoRA adaptörü olduğunu anlayıp base model + senin ağırlıklarını otomatik birleştirecek.
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=PREVIOUS_MODEL_PATH,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)

def apply_chat_template(example):
    raw_messages = example.get('messages', example.get('conversations', []))

    # ✉ KRİTİK DÜZELTME: Rolleri Qwen'in anladığı formata zorluyoruz
    standardized_messages = []
    for msg in raw_messages:
        role = msg.get('role', msg.get('from', '')).lower()
        content = msg.get('content', msg.get('value', ''))

        # Ne olursa olsun standart isimlere çevir
        if role in ['human', 'user']:
            role = 'user'
        elif role in ['gpt', 'assistant', 'model', 'bot']:
            role = 'assistant'

        standardized_messages.append({"role": role, "content": content})

    # System prompt ekle
    if len(standardized_messages) > 0 and standardized_messages[0].get('role') != 'system':
        standardized_messages = [system_message] + standardized_messages

    text = tokenizer.apply_chat_template(
        standardized_messages,
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": text}

# ========================
# 3. VERİ SETİNİ YÜKLEME VE BÖLME
# ========================
print(f"{DATASET_NAME} veri seti yükleniyor...")
raw_dataset = load_dataset(DATASET_NAME, split="train")
raw_val_dataset = load_dataset(DATASET_NAME, split="validation")
raw_test_dataset = load_dataset(DATASET_NAME, split="test")

dataset = raw_dataset
val_dataset = raw_val_dataset
test_dataset = raw_test_dataset

print("Veri seti ChatML formatına çevriliyor...")
# RAM şişmesini önlemek için num_proc=4 yerine 2'ye düşürüldü
dataset = dataset.map(apply_chat_template)
val_dataset = val_dataset.map(apply_chat_template)
test_dataset = test_dataset.map(apply_chat_template)

# ========================
# 4. EĞİTİM ARGÜMANLARI VE TRAINER
# ========================
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUMULATION,
    num_train_epochs=EPOCHS,
    learning_rate=LEARNING_RATE,
    fp16=use_fp16,
    bf16=use_bf16,
    logging_steps=LOGGING_STEPS,
    save_strategy="epoch", # Her epoch sonu kaydet
    save_total_limit=10, # En son 3 modeli tut                      BURAYI UNUTMAAA
    optim="adamw_8bit",
    weight_decay=0.05, # Overfit'i önlemek için 0.01'den 0.05'e artırıldı
    lr_scheduler_type="cosine",
    gradient_checkpointing=True,
    report_to="none",
    eval_strategy="epoch", # Her epoch sonu eval yap
    dataloader_num_workers=4,  # Windows'ta multiprocessing hatalarını sıfıra indirir
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    eval_dataset=val_dataset, # validation setini verdik
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    dataset_num_proc=4,  # RAM tasarrufu için 2'ye düşürüldü
    packing=True,
    args=training_args,
)

# === KAYIP MASKELEME ===
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
)

# ========================
# 5. EĞİTİMİ BAşALAT
# ========================
torch.cuda.empty_cache()
print("\n˘˘˘˘ Eğitime başalanıyor...")
trainer.train()

model.save_pretrained(FINAL_SAVE_PATH)
tokenizer.save_pretrained(FINAL_SAVE_PATH)
print(f"✅ Eğİtim tamamlandı! Model {FINAL_SAVE_PATH} dizinine kaydedildi.")

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

# ========================
# 6. TEST VE DEĞERLENDİRME
# ========================
print("\nTest veri seti üzerinde detaylı metrikler hesaplanıyor...")
semantic_model = SentenceTransformer("all-MiniLM-L6-v2")
rouge = evaluate.load("rouge")

FastLanguageModel.for_inference(model)
model.eval()  # 🔧 inference moduna aldık

# 🔧 GPU varsa kullan (yoksa zaten CPU'da devam eder)
device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)

security_keywords = ["vulnerability", "cve", "injection", "xss", "owasp", "exploit", "patch", "secure"]

pred_classes = []
label_classes = []
decoded_preds = []
decoded_labels = []

tokenizer.padding_side = "left"
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

TEST_SIZE = len(test_dataset)
test_subset = test_dataset.select(range(TEST_SIZE))

print(f"\n{len(test_subset)} veri üzerinde toplu (batch) test başalanıyor...\n")

for i in tqdm(range(0, len(test_subset), EVAL_BATCH_SIZE), desc="Değeriendiriliyor"):
    batch_dict = test_subset[i: i + EVAL_BATCH_SIZE]

    prompts = []
    expected_answers = []

    for example_msgs in batch_dict.get("messages", batch_dict.get("conversations", [])):

        standardized_msgs = []
        for msg in example_msgs:
            role = msg.get('role', msg.get('from', '')).lower()
            content = msg.get('content', msg.get('value', ''))

            if role in ['human', 'user']:
                role = 'user'
            elif role in ['gpt', 'assistant', 'model', 'bot']:
                role = 'assistant'

            standardized_msgs.append({"role": role, "content": content})

        if len(standardized_msgs) > 0 and standardized_msgs[0].get('role') != 'system':
            eval_messages = [system_message] + standardized_msgs[:-1]
        else:
            eval_messages = standardized_msgs[:-1]

        expected_answers.append(standardized_msgs[-1]["content"])

        prompt = tokenizer.apply_chat_template(
            eval_messages,
            tokenize=False,
            add_generation_prompt=True
        )
        prompts.append(prompt)

    inputs = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=MAX_SEQ_LENGTH
    ).to(device)

    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=MAX_EVAL_TOKENS,
            do_sample=False,
            use_cache=True,
            pad_token_id=tokenizer.pad_token_id
        )

    input_length = inputs.input_ids.shape[1]
    generated_tokens = outputs[:, input_length:]
    generated_texts = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)

    for gen_text, exp_ans in zip(generated_texts, expected_answers):
        clean_gen = gen_text.strip()
        clean_exp = exp_ans.strip()

        decoded_preds.append(clean_gen)
        decoded_labels.append(clean_exp)

        pred_classes.append(1 if any(kw in clean_gen.lower() for kw in security_keywords) else 0)
        label_classes.append(1 if any(kw in clean_exp.lower() for kw in security_keywords) else 0)

# ========================
# 📏 ORTALAMA TOKEN UZUNLUĞU HESAPLAMA
# ========================

lengths = [len(tokenizer.encode(x)) for x in decoded_labels]

avg_length = sum(lengths) / len(lengths)
max_length_sample = max(lengths)

print("\n📊 Ground Truth Uzunluk Analizi:")
print(f"Ortalama token sayısı : {avg_length:.2f}")
print(f"Max token sayısı      : {max_length_sample}")

# ========================
# 🔧 SEMANTIC SIMILARITY (BATCH HALİNE GETİRİLDİ)
# ========================
print("\nSemantic similarity hesaplanıyor...")

# 🔧 Tek tek encode yerine toplu encode (ÇOK BÜYÜK hız farkı)
emb_preds = semantic_model.encode(
    decoded_preds,
    batch_size=32,
    convert_to_tensor=True,
    show_progress_bar=True
)

emb_labels = semantic_model.encode(
    decoded_labels,
    batch_size=32,
    convert_to_tensor=True,
    show_progress_bar=True
)

semantic_scores = [
    util.cos_sim(p, l).item()
    for p, l in zip(emb_preds, emb_labels)
]

# ========================
# 7. SONUÇLARI YAZDIR
# ========================
acc = accuracy_score(label_classes, pred_classes)
f1 = f1_score(label_classes, pred_classes, zero_division=0)
precision = precision_score(label_classes, pred_classes, zero_division=0)
recall = recall_score(label_classes, pred_classes, zero_division=0)

if any(len(p) == 0 for p in decoded_preds):
    decoded_preds = [p if len(p) > 0 else "empty" for p in decoded_preds]

rouge_results = rouge.compute(predictions=decoded_preds, references=decoded_labels)

avg_semantic = sum(semantic_scores) / len(semantic_scores) if semantic_scores else 0

print("\n" + "=" * 45)
print(f"SECURECODE-WEB TEST SONUÇLARI ({TEST_SIZE} ÖRNEK)")
print("=" * 45)
print(f"Accuracy (Doğruluk)       : {acc:.4f}")
print(f"F1 Score                  : {f1:.4f}")
print(f"Precision (Kesinlik)      : {precision:.4f}")
print(f"Recall (Duyarlılık)       : {recall:.4f}")
print("-" * 45)
print(f"ROUGE-1 (Kelime Kesişimi) : {rouge_results['rouge1']:.4f}")
print(f"ROUGE-L (Cümle Yapısı)    : {rouge_results['rougeL']:.4f}")
print("-" * 45)
print(f"Semantic Similarity (Mean): {avg_semantic:.4f} (Üzerinden 1.0)")
print("=" * 45 + "\n")

from google.colab import runtime
runtime.unassign()